//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.DonHangChiTiets = new HashSet<DonHangChiTiet>();
        }
    
        public string MaDonHang { get; set; }
        public string MaNguoiDung { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string TrangThai { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string DienThoai { get; set; }
        public string GhiChu { get; set; }
        public string HoTenNguoiNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
