//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonViTinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonViTinh()
        {
            this.SanPhams = new HashSet<SanPham>();
        }

        [Required(ErrorMessage = "Mã đơn vị tính không được để trống!")]
        [StringLength(20, ErrorMessage = "Mã đơn vị tính tối đa 20 ký tự!")]
        public string MaDonViTinh { get; set; }

        [Required(ErrorMessage = "Tên đơn vị tính không được để trống!")]
        [StringLength(50, ErrorMessage = "Tên đơn vị tính tối đa 50 ký tự!")]
        public string TenDonViTinh { get; set; }

        [StringLength(250, ErrorMessage = "Mô tả tối đa 250 ký tự")]
        public string MoTa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
