//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgriEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DonHangChiTiets = new HashSet<DonHangChiTiet>();
            this.GioHangChiTiets = new HashSet<GioHangChiTiet>();
        }

        [Required(ErrorMessage = "Mã sản phẩm không được để trống!")]
        [StringLength(20, ErrorMessage = "Mã sản phẩm tối đa 20 ký tự!")]
        public string MaSanPham { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm không được để trống!")]
        [StringLength(150, ErrorMessage = "Tên sản phẩm tối đa 150 ký tự!")]
        public string TenSanPham { get; set; }

        [Required(ErrorMessage = "Giá không được để trống!")]
        [Range(0, 1000000000, ErrorMessage = "Giá phải >= 0")]
        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> Gia { get; set; }

        [Required(ErrorMessage = "Số lượng không được để trống!")]
        [Range(0, 100000, ErrorMessage = "Số lượng phải >= 0")]
        public Nullable<int> SoLuong { get; set; }

        [Required(ErrorMessage = "Phải chọn đơn vị tính!")]
        public string MaDonViTinh { get; set; }

        [StringLength(2000, ErrorMessage = "Mô tả tối đa 2000 ký tự!")]
        public string MoTa { get; set; }

        public string HinhAnh { get; set; }

        [Required(ErrorMessage = "Phải chọn danh mục!")]
        public string MaDanhMuc { get; set; }
        public string MaNguoiTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> ConHang { get; set; }
        public Nullable<bool> DaDuyet { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayTao { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangChiTiet> GioHangChiTiets { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
